[package]
name = "sensor-lib"
version.workspace = true
edition.workspace = true

[dependencies]
heapless = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
