# [build]
# target = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor --log-format=defmt"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
]

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor --log-format=defmt"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["alloc", "core"]

[env]
DEFMT_LOG="info"
